﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers.FastTree;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace FishSpecificationModelTrain
{
    public partial class FishNamePredictor
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.ReplaceMissingValues(new []{new InputOutputColumnPair(@"Weight", @"Weight"),new InputOutputColumnPair(@"Length1", @"Length1"),new InputOutputColumnPair(@"Length2", @"Length2"),new InputOutputColumnPair(@"Length3", @"Length3"),new InputOutputColumnPair(@"Height", @"Height"),new InputOutputColumnPair(@"Width", @"Width")})      
                                    .Append(mlContext.Transforms.Concatenate(@"Features", new []{@"Weight",@"Length1",@"Length2",@"Length3",@"Height",@"Width"}))      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"Species", @"Species"))      
                                    .Append(mlContext.MulticlassClassification.Trainers.OneVersusAll(binaryEstimator:mlContext.BinaryClassification.Trainers.FastTree(new FastTreeBinaryTrainer.Options(){NumberOfLeaves=6,MinimumExampleCountPerLeaf=11,NumberOfTrees=4,MaximumBinCountPerFeature=499,LearningRate=0.374491050882133F,FeatureFraction=0.999573939209049F,LabelColumnName=@"Species",FeatureColumnName=@"Features"}), labelColumnName: @"Species"))      
                                    .Append(mlContext.Transforms.Conversion.MapKeyToValue(@"PredictedLabel", @"PredictedLabel"));

            return pipeline;
        }
    }
}
