// This file was auto-generated by ML.NET Model Builder. 
using Microsoft.ML;
using Microsoft.ML.Data;
using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
namespace FishSpecificationModelTrain
{
    public partial class FishNamePredictor
    {
        /// <summary>
        /// model input class for FishNamePredictor.
        /// </summary>
        #region model input class
        public class ModelInput
        {
            [ColumnName(@"Species")]
            public string Species { get; set; }

            [ColumnName(@"Weight")]
            public float Weight { get; set; }

            [ColumnName(@"Length1")]
            public float Length1 { get; set; }

            [ColumnName(@"Length2")]
            public float Length2 { get; set; }

            [ColumnName(@"Length3")]
            public float Length3 { get; set; }

            [ColumnName(@"Height")]
            public float Height { get; set; }

            [ColumnName(@"Width")]
            public float Width { get; set; }

        }

        #endregion

        /// <summary>
        /// model output class for FishNamePredictor.
        /// </summary>
        #region model output class
        public class ModelOutput
        {
            [ColumnName("PredictedLabel")]
            public string Prediction { get; set; }

            public float[] Score { get; set; }
        }

        #endregion

        private static string MLNetModelPath = Path.GetFullPath("fishNamePredictor.zip");

        public static readonly Lazy<PredictionEngine<ModelInput, ModelOutput>> PredictEngine = new Lazy<PredictionEngine<ModelInput, ModelOutput>>(() => CreatePredictEngine(), true);

        /// <summary>
        /// Use this method to predict on <see cref="ModelInput"/>.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns><seealso cref=" ModelOutput"/></returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var predEngine = PredictEngine.Value;
            return predEngine.Predict(input);
        }

        private static PredictionEngine<ModelInput, ModelOutput> CreatePredictEngine()
        {
            var mlContext = new MLContext();
            ITransformer mlModel = mlContext.Model.Load(MLNetModelPath, out var _);
            return mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);
        }
    }
}
